name: jonh_assistant
description: Assistente de voz local Jonh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Audio
  record: ^6.0.0
  just_audio: ^0.9.36
  permission_handler: ^11.0.1
  
  # Network
  web_socket_channel: ^2.4.0
  http: ^1.1.2
  
  # State Management
  provider: ^6.1.1
  
  # Wake Word (Porcupine)
  porcupine_flutter: ^3.0.0
  
  # Utils
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.0
  package_info_plus: ^8.0.0
  
  # Background Service
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/wake_words/

